#include "../include/debug.h"
#include "../include/types.h"
#include "../include/matrix_operations.h"
#include "../include/vector_operations.h"
#include "../include/coordinates.h"
#include "../include/clipping.h"
#include "../include/virtual_camera.h"
